OEL-1724: Create publication content type
openeuropa/oe_starter_content pull request #12
Opened 2022-06-22 12:01 UTC by escuriola

2022-06-23 14:10 UTC, brummbar requested changes

2022-06-23 14:10 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    var_dump($page->getHtml());
😄

2022-06-23 14:10 UTC, brummbar commented on modules/oe_starter_content_publication/config/install/field.field.node.oe_sc_publication.oe_documents.yml
> +required: false
This should be required, cardinality 1. Probably we need to create a separate field.

2022-06-23 14:10 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $assert_session->elementExists('css', 'time');
This is where we should assess the date.

2022-06-23 14:10 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $page->fillField('Title', 'Fusce commodo aliquam arcu');
Let's not use lorem ipsum, let's use normal text like "Example publication page".

2022-06-23 14:10 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $page->fillField('Short description', 'Fusce a quam. Fusce vel dui. Suspendisse nisl elit, rhoncus eget.');
Same for this and the other fields that have lorem ipsum.

2022-06-23 14:10 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $nid = basename($url);
I don't like this much, let's use $this->getNodeByTitle().

2022-06-23 14:10 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $this->assertMatchesRegularExpression("/\d+\/\d+\/\d+/", $publication_date->getText());
These are the lines we can move above.

2022-06-28 15:59 UTC, brummbar requested changes

2022-06-28 15:59 UTC, brummbar commented on modules/oe_starter_content_publication/config/install/field.storage.node.oe_sc_publication_document.yml
> +type: oe_featured_media
This shouldn't be a featured media, just a normal entity reference field.

2022-06-28 15:59 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $assert_session->pageTextContains('Title field is required.');
The errors are 3, I expect we assert the 3 messages here.
And since we need to change the storage, they will be 2.

2022-06-28 15:59 UTC, brummbar commented on tests/src/Functional/PublicationTest.php
> +    $this->drupalGet('/node/' . $node->id());
```suggestion
    $this->drupalGet($node->toUrl());
```

2022-06-29 17:38 UTC, brummbar requested changes
All looks good but the last commit with the field rename. The field already has `oe_` prefixed to it, there's no need to add yet another oe in the name.

2022-06-30 14:23 UTC, brummbar submitted a review, later dismissed

2022-07-01 11:36 UTC, drishu requested changes

2022-07-01 11:36 UTC, drishu commented on modules/oe_starter_content_publication/config/install/field.storage.node.oe_sc_publication_document.yml
> +langcode: en
so, I looked into it also, the other oe_document storages did not match requirements, had either a different cardinality or a different target_type

2022-07-01 11:36 UTC, drishu commented on modules/oe_starter_content_publication/oe_starter_content_publication.info.yml
> +  - oe_content:oe_content_documents_field
where is this used ?

2022-07-01 11:36 UTC, drishu commented on modules/oe_starter_content_publication/oe_starter_content_publication.info.yml
> +    - node.type.oe_sc_publication
sor these pls

2022-07-01 11:36 UTC, drishu commented on tests/src/Functional/PublicationTest.php
> +    $publication_date = $page->find('css', 'time');
this is a bit odd as requirement says only date, we will override in whitelabel anyhow sure, but lets display only date and assert only the date. No time pls.

2022-07-02 17:36 UTC, drishu commented on tests/src/Functional/PublicationTest.php
> +    $this->assertMatchesRegularExpression("/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/", $publication_date->getText());
I know why we are using regex here, but honestly I dont like it, better for me would be 
`$this->assertSame(date('Y-m-d'), $publication_date->getText());`
or even better than that use 
`drupal/datetime_testing`
I'll have to discuss this in the team

2022-07-04 11:38 UTC, drishu commented on tests/src/Functional/PublicationTest.php
> +    $this->assertMatchesRegularExpression("/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/", $publication_date->getText());
Ok, so conclusion, use https://www.drupal.org/project/datetime_testing, this way you can set a static date and check for it, see how it was done here https://github.com/openeuropa/oe_theme/blob/4d2c9e54a2f22d9d2c08490dc66786ed40359003/tests/src/Kernel/ConsultationRenderTest.php#L66

2022-07-05 08:30 UTC, drishu submitted a review, later dismissed

2022-07-05 08:44 UTC, drishu approved these changes

2022-07-05 09:05 UTC, brummbar approved these changes

2022-07-05 09:06 UTC, merged