OEL-1910: Drupal 9.4 support.
openeuropa/oe_starter_content pull request #22
Opened 2022-09-19 11:02 UTC by drishu

2022-09-28 14:34 UTC, brummbar requested changes

2022-09-28 14:34 UTC, brummbar commented on composer.json
>          "openeuropa/oe_media": "^1.14"
oe_content requires this at ^1.15, which bumps file_link to 2.0.4, which means we can get rid of line 66

2022-09-28 15:18 UTC, brummbar requested changes

2022-09-28 15:18 UTC, brummbar commented on composer.json
>          "openeuropa/code-review": "^1.6 || ^2.0",
Actually noticed that now we can use only ^2.0, which means also we can get rid of openeuropa/code-review.

2022-09-29 06:58 UTC, drishu commented on composer.json
>          "openeuropa/code-review": "^1.6 || ^2.0",
we can get rid of the 1.6 but not the entire thing unfortunately

2022-09-29 08:00 UTC, merged