OEL-1290: Content types and tests renamed for oe_content.
openeuropa/oe_starter_content pull request #5
Opened 2022-03-10 09:37 UTC by Maxfire

Config files and tests modified to make oe_content_event and oe_content_news work.

2022-03-10 13:09 UTC, drishu requested changes

2022-03-10 13:09 UTC, drishu commented on modules/oe_starter_content_news/config/install/field.field.node.oe_sc_news.oe_featured_media.yml
> -    - field.storage.node.oe_featured_media
this cought my eye, pls, re-export the configuration:
docker-compose exec web ./vendor/bin/drush cde oe_starter_content_event
docker-compose exec web ./vendor/bin/drush cde oe_starter_content_news

2022-03-10 13:09 UTC, drishu commented on modules/oe_starter_content_event/config/install/core.entity_form_display.node.oe_sc_event.default.yml
> +uuid: fcf74725-6587-40c3-95a3-9b74b5fbe7ca
pls use config_devel to export configuration from now on

2022-03-10 13:09 UTC, drishu commented on modules/oe_starter_content_news/oe_starter_content_news.info.yml
> +  - openeuropa:oe_media_avportal
sort this list

2022-03-10 13:09 UTC, drishu commented on modules/oe_starter_content_event/oe_starter_content_event.info.yml
> +  - oe_content:oe_content
sort this list

2022-03-10 13:09 UTC, drishu commented on modules/oe_starter_content_event/oe_starter_content_event.info.yml
> +    - core.entity_form_display.node.oe_sc_event.default
sort this list

2022-03-10 13:09 UTC, drishu commented on composer.json
> +        "drupal/entity_browser": "^2.6",
this comes under drupal/core-dev, sort this pls

2022-03-10 13:09 UTC, drishu commented on tests/src/Functional/NewsIntegrationTest.php
> -    $assert_session->pageTextContains('01/24/2022 - 00:00');
this is a difference in functionality, see https://github.com/openeuropa/oe_content/blob/2.x/config/install/field.storage.node.oe_publication_date.yml#L12 but since its not part of the requirements I think its ok. Do report this in a ticket comment though

2022-03-10 14:08 UTC, drishu requested changes

2022-03-10 14:08 UTC, drishu commented on composer.json
> +        "amphp/parallel-functions": "~1.0.0"
this should be on top

2022-03-10 14:59 UTC, drishu submitted a review, later dismissed

2022-03-10 20:04 UTC, brummbar requested changes
Look

2022-03-10 20:04 UTC, brummbar commented on modules/oe_starter_content_event/config/install/field.field.node.oe_sc_event.oe_location.yml
> +id: node.oe_sc_event.oe_location
This should be renamed oe_sc_location, or better. Let's name it oe_sc_event_location, to mimic oe_content ones.

2022-03-10 20:04 UTC, brummbar commented on oe_starter_content.info.yml
>    - drupal:address
We actually don't have any fields in here anymore, so there are no dependencies to add.
They need to be moved to the related submodules now.

2022-03-14 08:19 UTC, brummbar approved these changes

2022-03-14 10:31 UTC, drishu approved these changes

2022-03-14 10:34 UTC, merged